# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Latlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=11)),
                ('lan', models.CharField(max_length=11)),
                ('updatedat', models.DateTimeField(default=datetime.datetime(2016, 6, 13, 12, 8, 42, 717000, tzinfo=utc))),
            ],
        ),
    ]
