# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlan',
            name='lan',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='latlan',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='latlan',
            name='updatedat',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 13, 13, 42, 43, 43000, tzinfo=utc)),
        ),
    ]
