# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20160613_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlan',
            name='updatedat',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 13, 13, 55, 59, 494000, tzinfo=utc)),
        ),
    ]
